"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['gui_main_001.py']
DATA_FILES = ["./config_ini.ini", "./datas", "./sessions"]
OPTIONS = {
    'packages': ['pytz', 'tzdata', 'apscheduler']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
