"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

import apscheduler

APP = ['gui_main.py']
DATA_FILES = ["./config_ini.ini"]
OPTIONS = {
    'packages': ['pytz', 'tzdata', 'apscheduler']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
